# When enables (true) the password file will be encrypted using GPG
gpg_passwordfile_enabled: false

# List of usernames/email to be used for the encryption as recipient
gpg_encryption_recipient_list: "['']"