---
- name: If user permission not received as yes, fail
  fail:
    msg: "The vault files and password files not deleted and new ones not generated. No permission received."
  when: "not 'yes' in delete_permission"

- name: "This will overwrite the vault and vault password files are you sure to continue"
  pause:
    prompt: |
          ***************************************************
                           ARE YOU SURE? 
                           Yes, press 'Enter'
                  If not then ctrl+C then 'A' = abort
                  If you are sure then (ctrl+C then 'C' = continue)
          ***************************************************

- name: Get the vault dir path
  set_fact:
    vault_dir: "{{ target_inventory }}/{{ target_vault | dirname }}" 

- name: Get stats of the Target Vault dir
  stat:
    path: "{{ vault_dir }}"
  register: vault_dir_stat

- name: The Vault dir is not present
  fail:
    msg: "The Vault dir {{ vault_dir }} is not present"
  when: vault_dir_stat.stat.isdir is not defined or not vault_dir_stat.stat.isdir

- name: Path Check Result
  debug:
    msg: "Path {{ vault_dir }} exists and is a directory"
  when: vault_dir_stat.stat.isdir is defined and vault_dir_stat.stat.isdir

- name: Get the vault password file path
  set_fact:
    vault_password_dir: "{{ target_vault_password_file | dirname }}" 

- name: Get stats of the Target Vault password dir
  stat:
    path: "{{ vault_password_dir }}"
  register: vault_password_dir_stat

- name: The Vault password file dir is not present
  fail:
    msg: "The Vault dir {{ vault_password_dir }} is not present"
  when: vault_password_dir_stat.stat.isdir is not defined or not vault_password_dir_stat.stat.isdir

- name: Path Check Result
  debug:
    msg: "Path {{ vault_password_dir }} exists and is a directory"
  when: vault_password_dir_stat.stat.isdir is defined and vault_password_dir_stat.stat.isdir

- name: Generate vault password, if not present
  set_fact:
    vault_passwd: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=62' ) }}"

- name: Copy Vault password template to localhost
  template:
    src: 'vault_passwd.yml.j2'
    dest: "{{ target_vault_password_file }}"
    mode: '640'
  no_log: 'yes'
  when: not gpg_passwordfile_enabled 

- name: Make sure that any clear text password files are not present when gpg is used
  file:
    path: "{{ target_vault_password_file }}"
    state: 'absent'
  when: gpg_passwordfile_enabled

- name: Copy Vault clear template to localhost
  template:
    src: 'vault.yml.j2'
    dest: "{{ target_inventory }}/{{ target_vault }}"
    mode: '640'
  no_log: 'no'  

- name: Copy ansible-vault.sh to be used with gpg
  template:
    src: 'gpg_ansible-vault.sh.j2'
    dest: "~/.ansible-vault.sh"
    mode: '750'
  when: gpg_passwordfile_enabled

- name: Copy ansible-vault.sh to be used with clear text
  template:
    src: 'txt_ansible-vault.sh.j2'
    dest: "~/.ansible-vault.sh"
    mode: '750'
  when: not gpg_passwordfile_enabled

- name: Make correctly formated recipient list string
  set_fact:
    recipient_list_str: "{{ recipient_list_str | default('') }} --recipient {{ item }}"
  loop: "{{ gpg_encryption_recipient_list }}"
  when: gpg_passwordfile_enabled

- debug:
    var: recipient_list_str
  when: gpg_passwordfile_enabled

- name: GPG encrypt the password file
  shell: "echo '{{ vault_passwd }}' | {{ gpg_command }} --encrypt {{ recipient_list_str }} -o {{ target_vault_password_file }}.gpg"
  no_log: 'yes'
  when: gpg_passwordfile_enabled

- name: Encrypt the Ansible vault by using clear txt password file
  command: 'ansible-vault encrypt --vault-password-file {{ target_vault_password_file }} --encrypt-vault-id default {{ target_inventory }}/{{ target_vault }}'
  no_log: 'yes'
  when: not gpg_passwordfile_enabled

- name: Encrypt the Ansible vault using pgp encrypted password file
  shell: 'ansible-vault encrypt --vault-password-file "$(cat {{ target_vault_password_file }})" --encrypt-vault-id default {{ target_inventory }}/{{ target_vault }}'
  no_log: 'yes'
  when: gpg_passwordfile_enabled

- pause:
    seconds: 1
    prompt: |
          =========================
          New clear text Ansible Vault password file created with a random password.
          The password file location: {{ target_vault_password_file }}

          New Ansible Vault created with generated random passwords.
          The Vault location: {{ target_inventory }}/{{ target_vault }}
          =========================
  when: not gpg_passwordfile_enabled 

- pause:
    seconds: 1
    prompt: |
          =========================
          New GPG encrypted Ansible Vault password file created with a random password.
          The password file location: {{ target_vault_password_file }}

          New Ansible Vault created with generated random passwords.
          The Vault location: {{ target_inventory }}/{{ target_vault }}
          =========================
  when: gpg_passwordfile_enabled        
