
target_inventory: '../MyFoE_inventory/development'

taget_vault: 'group_vars/all/vault.yml'
target_vault_password_file: '~/.development_vault_password.txt'

# When enables (true) the password file will be encrypted using GPG
gpg_passwordfile_enabled: false

# List of usernames/email to be used for the encryption as recipient
gpg_encryption_recipient_list: "[]"

# GPG command and path if needed e.g. gpg or gpg2
gpg_command: 'gpg'

vault_content:
  Ansible_User:
    comment: 'Ansible user password (e.g. Sudo)'
    key: 'vault_ansible_user_password' 
    value: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=32' ) }}"
  CA:
    comment: 'CA Private Key password'
    key: 'vault_ca_private_key_password'
    value: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=62' ) }}"
  CA_dir_encr:
    comment: 'CA Dir Encryption'
    key: 'vault_ca_dir_encryption_password'
    value: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=62' ) }}"
  Server_PKI:
    comment: 'Server Private Key password'
    key: 'vault_server_pki_private_key_password_{{ inventory_hostname }}'
    value: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=62' ) }}"