
target_inventory: '../MyFoE_inventory/development'

taget_vault: 'group_vars/all/vault.yml'
target_vault_password_file: '~/.development_vault_password.txt'

# When enables (true) the password file will be encrypted using GPG
gpg_passwordfile_enabled: false

# List of usernames/email to be used for the encryption as recipient
gpg_encryption_recipient_list: "[]"

# GPG command and path if needed e.g. gpg or gpg2
gpg_command: 'gpg'

vault_content_general:
  Ansible_User:
    comment: 'Ansible user password (e.g. Sudo)'
    name: 'vault_ansible_user_password' 
    password_type: 'normal'

vault_content_host:
  CA:
    comment: 'CA Private Key password'
    name: 'vault_ca_private_key_password'
    password_type: 'normal'
    host: 
      - ca
  CA_dir_encr:
    comment: 'CA Dir Encryption'
    name: 'vault_ca_dir_encryption_password'
    password_type: 'normal'
    host: 
      - ca
  Server_PKI:
    comment: 'Server Private Key password'
    name: 'vault_server_pki_private_key_password'
    password_type: 'simple'
    host:
      - ca
      - tester1
      - tester2
  
